### ISSUE TITLE
Code broken

### ISSUE THREAD

**Issue by lucasjinreal** [luka-group/mDPO#6] opened 2024-10-28 13:56 UTC
TypeError: mDPODataCollatorBunny.__init__() got an unexpected keyword argument 'max_prompt_length'
seems just latest trl not support any longer? How to modify it

**Comment by FeiWang96** [comment] 2024-11-10 19:14
Hi,

The current code is based on `trl==0.7.2`. Using a later version may cause errors. Updating the trl and transformer version is on our to-do list, but we currently don’t have the bandwidth to handle it. If you're interested in doing it, we’d be happy to support you. 

Closed as this issue is a duplicate of #7 .

**Closed by FeiWang96** 2024-11-10 19:14 UTC

**Comment by lucasjinreal** [comment] 2024-11-13 14:09
Is there any time scheduler on adopt to latest trl version? It's a huge broken now. I'd like to help but don't know how to modify while maintain same result for replication.
